r"""
Zoomies - turning a settings dict into a script, and running it.

The contract with the rest of the app is deliberately narrow: backends build a
LaunchPlan (which is just text plus some metadata), and this module writes it
to disk and runs it. Nothing here knows what a model is.

Two execution shapes:

  short-lived   ollama create / load / rm. We wait for the exit code and read
                the output back.

  long-lived    the Unsloth server. We start it and walk away. The script
                redirects its own output to a log file and the GUI tails that
                file, so closing Zoomies cannot break a pipe and kill the
                server, and a restarted Zoomies can pick the log back up.
"""

import os
import re
import subprocess
import time
from dataclasses import dataclass, field

import state

CREATE_NO_WINDOW = 0x08000000
CREATE_NEW_PROCESS_GROUP = 0x00000200

# -NoProfile       a profile that prints a banner would corrupt anything we
#                  parse, and it costs startup time we do not need.
# -NonInteractive  stops a hidden window sitting forever on a prompt nobody
#                  can see.
# -ExecutionPolicy Bypass  required: the default Restricted policy refuses
#                  -File outright, and this user has no reason to have
#                  changed it.
POWERSHELL = [
    "powershell", "-NoProfile", "-NonInteractive",
    "-ExecutionPolicy", "Bypass", "-File",
]

# Exit codes the generated scripts use, so the GUI can say something better
# than "it failed". Kept here because the generator and the reader both need
# to agree on them.
EXIT_MEANING = {
    0: "",
    1: "the command reported an error",
    3: "the Ollama server did not start",
    4: "the port is already in use",
    5: "the model file was not found",
    6: "creating the temporary tag failed",
}

API_KEY_RE = re.compile(r"\b(sk-[A-Za-z0-9_\-]{16,})")
ERROR_RE = re.compile(
    r"(?i)\b(error|failed|fatal|exception|traceback|cannot|denied|refused|unable)\b"
)


@dataclass
class LaunchPlan:
    """Everything needed to run one action.

    script_text is the whole truth - the user can read it in Preview before
    anything happens.
    """

    kind: str                       # "load" | "stop"
    backend: str
    script_text: str
    script_path: str
    log_path: str
    endpoint: str = ""
    host: str = "127.0.0.1"
    port: int = 0
    long_lived: bool = False
    creates_tag: str = ""           # Ollama: tag to record for later cleanup
    removes_tag: str = ""           # Ollama: tag this script deletes
    notes: list = field(default_factory=list)   # warnings shown BEFORE running


@dataclass
class RunResult:
    ok: bool
    returncode: int
    pid: int = 0
    lines: list = field(default_factory=list)
    message: str = ""


# --------------------------------------------------------------------------
# PowerShell text helpers
# --------------------------------------------------------------------------

def ps_single(value):
    """Quote a value as a PowerShell single-quoted string.

    Single quotes are the safe choice: PowerShell does no expansion inside
    them, so a model path containing a dollar sign or a backtick stays
    literal. The only escape needed is doubling an embedded single quote.
    """
    return "'" + str(value).replace("'", "''") + "'"


def slugify(text, limit=40):
    s = re.sub(r"[^A-Za-z0-9._-]+", "-", str(text)).strip("-")
    return (s[:limit] or "model").lower()


def new_paths(backend, label):
    """Matching script/log names, so a log is always traceable to its script."""
    state.ensure_dirs()
    stamp = time.strftime("%Y%m%d-%H%M%S")
    base = "%s_%s_%s" % (backend, slugify(label), stamp)
    return (
        os.path.join(state.SCRIPT_DIR, base + ".ps1"),
        os.path.join(state.LOG_DIR, base + ".log"),
    )


def header(title, model, source_note=""):
    lines = [
        "# Generated by Zoomies - %s" % time.strftime("%Y-%m-%d %H:%M:%S"),
        "# Action: %s" % title,
        "# Model:  %s" % model,
    ]
    if source_note:
        lines.append("# Source: %s" % source_note)
    lines.append("# Regenerate from the app; edits here are lost on the next run.")
    return "\n".join(lines)


# --------------------------------------------------------------------------
# execution
# --------------------------------------------------------------------------

def write_script(plan):
    state.ensure_dirs()
    with open(plan.script_path, "w", encoding="utf-8") as fh:
        fh.write(plan.script_text)
    return plan.script_path


def run_script(plan, on_line=None, timeout=600):
    """Run a short-lived script to completion and collect its output.

    stderr is folded into stdout because the generated scripts already send
    every PowerShell stream to the log; what comes back on the pipe is a
    convenience for the GUI, not the record of truth.
    """
    write_script(plan)
    lines = []
    try:
        proc = subprocess.Popen(
            POWERSHELL + [plan.script_path],
            stdout=subprocess.PIPE, stderr=subprocess.STDOUT,
            stdin=subprocess.DEVNULL,
            text=True, encoding="utf-8", errors="replace",
            creationflags=CREATE_NO_WINDOW,
        )
    except OSError as exc:
        return RunResult(False, -1, message="Could not start PowerShell: %s" % exc)

    try:
        for raw in proc.stdout:
            line = raw.rstrip("\r\n")
            lines.append(line)
            if on_line:
                on_line(line)
        proc.wait(timeout=timeout)
    except subprocess.TimeoutExpired:
        proc.kill()
        return RunResult(False, -1, proc.pid, lines, "Timed out after %ds" % timeout)
    except OSError as exc:
        return RunResult(False, -1, proc.pid, lines, str(exc))

    rc = proc.returncode
    msg = EXIT_MEANING.get(rc, "exit code %d" % rc) if rc else ""
    return RunResult(rc == 0, rc, proc.pid, lines, msg)


def spawn_script(plan):
    """Start a long-lived script and return the PowerShell PID.

    We do not read its stdout: the script writes its own log, and an unread
    pipe is exactly how you wedge a child process. CREATE_NEW_PROCESS_GROUP
    keeps a Ctrl-C aimed at Zoomies from reaching the server.
    """
    write_script(plan)
    try:
        proc = subprocess.Popen(
            POWERSHELL + [plan.script_path],
            stdout=subprocess.DEVNULL, stderr=subprocess.DEVNULL,
            stdin=subprocess.DEVNULL,
            creationflags=CREATE_NO_WINDOW | CREATE_NEW_PROCESS_GROUP,
        )
    except OSError as exc:
        return RunResult(False, -1, message="Could not start PowerShell: %s" % exc)
    return RunResult(True, 0, proc.pid)


def tail_log(path, on_line, cancel, from_end=False, poll=0.15):
    """Follow a log file, surviving the file not existing yet.

    from_end is used when re-attaching to a server that was already running
    before this Zoomies session started - replaying a huge log would be both
    slow and wrong.
    """
    handle = None
    try:
        while not cancel.is_set():
            if handle is None:
                try:
                    handle = open(path, "r", encoding="utf-8-sig", errors="replace")
                    if from_end:
                        handle.seek(0, os.SEEK_END)
                except OSError:
                    cancel.wait(0.5)
                    continue
            line = handle.readline()
            if line:
                on_line(line.rstrip("\r\n"))
            else:
                cancel.wait(poll)
    finally:
        if handle is not None:
            try:
                handle.close()
            except OSError:
                pass


def read_log_tail(path, max_lines=400):
    try:
        with open(path, "r", encoding="utf-8-sig", errors="replace") as fh:
            return fh.read().splitlines()[-max_lines:]
    except OSError:
        return []


def find_api_key(lines):
    """Unsloth prints its API key to stdout; the user needs it to point any
    client at the server, and it would otherwise be buried in a log file."""
    for line in reversed(lines):
        m = API_KEY_RE.search(line)
        if m:
            return m.group(1)
    return ""


def looks_like_error(line):
    return bool(ERROR_RE.search(line))


def powershell_available():
    """Checked once at startup.

    A corporate policy can still block -File even with -ExecutionPolicy
    Bypass, and the user deserves to be told that in words rather than
    watching every Load silently fail.
    """
    try:
        res = subprocess.run(
            ["powershell", "-NoProfile", "-NonInteractive", "-Command",
             "Write-Output ZOOMIES_OK"],
            capture_output=True, text=True, timeout=25,
            creationflags=CREATE_NO_WINDOW,
        )
    except (OSError, subprocess.SubprocessError) as exc:
        return False, "PowerShell could not be started (%s)" % exc
    if "ZOOMIES_OK" in (res.stdout or ""):
        return True, ""
    return False, (res.stderr or res.stdout or "PowerShell returned nothing").strip()[:200]
